version: '3.8'

services:
  registry:
    image: registry:2
    container_name: local-registry
    restart: always
    volumes:
      - ./data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
    networks:
      - registry-net

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: always
    environment:
      REGISTRY_TITLE: Local Docker Registry
      REGISTRY_URL: "/"  # UI vai usar o proxy
      DELETE_IMAGES: "true"
    networks:
      - registry-net

  nginx:
    image: nginx:alpine
    container_name: registry-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - registry
      - registry-ui
    networks:
      - registry-net

networks:
  registry-net:
    driver: bridge
