version: '3'

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./stirlingpdf/config:/configs
      - ./stirlingpdf/customFiles:/customFiles/
      - ./stirlingpdf/logs:/logs/
      - ./stirlingpdf/tmp:/tmp/
    environment:
      - DOCKER_ENABLE_SECURITY=false  # Defina como true em produção
